version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    registries: "*"
    cooldown: 7
    groups:
      gradle-updates:
        exclude-patterns:
          - "uk.gov.laa.*"
      internal-packages:
        patterns:
          - "uk.gov.laa.*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown: 7
    groups:
      github-actions:
        patterns:
          - "**"
