version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    registries: "*"
    cooldown:
      default-days: 0
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 2
    groups:
      gradle-updates:
        exclude-patterns:
          - "uk.gov.laa.*"
      internal-packages:
        patterns:
          - "uk.gov.laa.*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 0
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 2
    groups:
      github-actions:
        patterns:
          - "**"
