spring:
  application:
    name: laa-ccms-api-gateway
    version: @version@

  # example database
  datasource:
    url: jdbc:h2:mem:itemsDb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  #do not auto create db schema, use .sql scripts
  jpa:
    hibernate:
      ddl-auto: none

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

sentry:
  dsn: # configure dsn url here
  environment: # configure environment name here

# ECS structured logging
logging:
  level:
    root: ${ROOT_LOGGING_LEVEL:info}
    org.springframework: ${SPRING_LOGGING_LEVEL:info}
    uk.gov.justice.laa.ccms.gateway: ${APP_LOGGING_LEVEL:info}
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: ${spring.application.name:default}
        version: ${spring.application.version:default}
        environment: ${spring.profiles.active:default}
        node_name: ${HOSTNAME:unknown}
