spring:
  application:
    name: laa-ccms-api-gateway
    version: @version@

  main:
    web-application-type: reactive
  cloud:
    discovery:
      enabled: false
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 20000
          routes:
            - id: applications
              uri: http://caab-api:8080/applications
              predicates:
                - Path=/applications/**

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

sentry:
  dsn: # configure dsn url here
  environment: # configure environment name here

# ECS structured logging
logging:
  level:
    root: ${ROOT_LOGGING_LEVEL:info}
    org.springframework: ${SPRING_LOGGING_LEVEL:info}
    uk.gov.justice.laa.ccms.gateway: ${APP_LOGGING_LEVEL:info}
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: ${spring.application.name:default}
        version: ${spring.application.version:default}
        environment: ${spring.profiles.active:default}
        node_name: ${HOSTNAME:unknown}
